services:
  nodeseek-monitor:
    image: ghcr.io/j2st1n/nodeseek-tg-monitor:latest
    # build: .  # 如需本地编译可取消此行注释并注释上一行
    container_name: nodeseek-monitor
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ./data:/app/data
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
