services:
  community-monitor:
    image: ghcr.io/j2st1n/community-tg-monitor:latest
    container_name: community-monitor
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ./data:/app/data
      - ./app:/app/app
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
